<?php
    $e = $this->element;
    $labelHelper = $this->formLabel();
    $label = $e->getLabel();
    $labelHelperTranlator = $labelHelper->getTranslator();
    if($label AND $labelHelperTranlator) {
        $label = $labelHelperTranlator->translate($label, $labelHelper->getTranslatorTextDomain());
    }
    $extended = $e->getOption('extended');
    if($e->getAttribute('type') == 'checkbox' || $e->getAttribute('type') == 'multi_checkbox') {
        $name = $e->getName().'[]';
        $values = $e->getValue();
        $type = 'checkbox';
    } else {
        $name = $e->getName();
        $values = array(0 => $e->getValue());
        $type = $e->getAttribute('type');
    }
    $err = (count($e->getMessages()) > 0) ? $e->getMessages() : false;

    $optionValues = $e->getOption('value_options');
?>
<div class="control-group">
    <?php if (empty($optionValues)): ?>
        <label class="control-label" for="<?php echo $e->getAttribute('id') ?>">
            <?php if($e->getAttribute('required') == 'required') echo '<em>*</em>'; ?><?php echo $label; ?>
        </label>
        <div class="controls">
            <?php if ($e->useHiddenElement()): ?>
                <input type="hidden" name="<?php echo $e->getName(); ?>" value="<?php echo $e->getUncheckedValue(); ?>"/>
            <?php endif; ?>
            <input type="<?php echo $e->getAttribute('type'); ?>"
                   id="<?php echo $e->getAttribute('id'); ?>"
                   name="<?php echo $e->getName(); ?>"
                   value="<?php echo $e->getCheckedValue(); ?>"
                   <?php if ($e->isChecked()): ?>checked="checked"<?php endif ?>/>
    <?php else: ?>
        <label class="control-label">
            <?php if($label) { ?><?php if($e->getAttribute('required') == 'required') { echo '<em>*</em>'; } ?><?= $label; ?><?php } ?>
        </label>
        <div class="controls">
        <?php if ($e->useHiddenElement()): ?>
            <input type="hidden" name="<?php echo $e->getName(); ?>" value="<?php echo $e->getUncheckedValue(); ?>"/>
        <?php endif; ?>
        <?php foreach($optionValues as $value => $key) { ?>
            <label class="<?= $type; ?><?php if($extended['compact']) { echo ' inline'; } ?>">
            <input type="<?= $type; ?>"
                   value="<?= $value; ?>" <?php if(is_array($values) && in_array($value, $values)){ echo 'checked="checked"'; } ?>
                   name="<?= $name; ?>" id="<?= $this->slugify($e->getName().'-'.$value); ?>">
            <?php if($labelHelperTranlator) {
                echo $labelHelperTranlator->translate($key, $labelHelper->getTranslatorTextDomain());
            } else {
                echo $key;
            } ?>
            </label>
        <?php } ?>
    <?php endif; ?>
    <?php if(count($extended['help']) > 0) { ?>
    <span class="help-block">
        <?php if($labelHelperTranlator) { 
            echo $labelHelperTranlator->translate($extended['help']['content'], $labelHelper->getTranslatorTextDomain());
        } else {
            echo $extended['help']['content'];
        } ?>
    </span>
    <?php } ?>
    <?php if($err) { ?>
    <ul>
    <?php foreach($err as $k => $v) { ?>
    	<li><?php if($labelHelperTranlator) { 
            echo $labelHelperTranlator->translate($v, $labelHelper->getTranslatorTextDomain());
        } else {
            echo $v;
        } ?></li>
    <?php } ?>
    </ul>
    <?php } ?>
    </div>
</div>