<?php
    $e = $this->element;
    $c = $e->getCaptcha();
    $c->generate();
    $labelHelper = $this->formLabel();
    $label = $e->getLabel();
    $labelHelperTranlator = $labelHelper->getTranslator();
    if($label AND $labelHelperTranlator) {
        $label = $labelHelperTranlator->translate($label, $labelHelper->getTranslatorTextDomain());
    }
    $extended = $e->getOption('extended');
    $required = ($e->getAttribute('required') == 'required') ? 'required="required"' : false;
    $err = (count($e->getMessages()) > 0) ? $e->getMessages() : false;
?>

<div class="ctrlHolder <?php if($err){ echo "error";}?> last">
    <label for="<?= $e->getAttribute('id'); ?>">
        <?php if($label) { ?><?php if($required) { echo '<em>*</em>'; } ?><?= $label; ?><?php } ?>
    </label>
    
    <ul <?php if($extended['compact']) { echo 'class="alternate"'; } ?>>
        
        <li>
            <img width="<?= $c->getWidth(); ?>" height="<?= $c->getHeight(); ?>" alt="<?= $c->getImgAlt(); ?>"
                src="<?= $c->getImgUrl() . $c->getId() . $c->getSuffix(); ?>">
        </li>
        <li>
            <?= $this->captchaInputs($e); ?>
        </li>
    </ul>
    
    <?php if(count($extended['help']) > 0) { ?>
    <p class="formHint">
        <?php if($labelHelperTranlator) { 
            echo $labelHelperTranlator->translate($extended['help']['content'], $labelHelper->getTranslatorTextDomain());
        } else {
            echo $extended['help']['content'];
        } ?>
    </p>
    <?php } ?>
    <?php if($err) { ?>
    <ul class="form-error">
    <?php foreach($err as $k => $v) { ?>
    	<li><?php if($labelHelperTranlator) { 
            echo $labelHelperTranlator->translate($v, $labelHelper->getTranslatorTextDomain());
        } else {
            echo $v;
        } ?></li>
    <?php } ?>
    </ul>
    <?php } ?>
</div>